AMEL2/Controllers/AntriebsartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace AMEL2.Controllers
{
    public class AntriebsartsController : Controller
    {
        private PandatasoftEntities db = new PandatasoftEntities();
        

        public List<SelectListItem> getListAntriebsart()
        {          
            List<tblAntriebsart> listAntriebsart = db.tblAntriebsart.ToList();            
            var lst = listAntriebsart.Select(x => new SelectListItem { Value = x.Antriebsart.ToString(), Text = x.Antriebsart.ToString() }).ToList();
            return lst;
        }
        // GET: Antriebsarts
        public ActionResult Index()
        {
            
            return View(db.tblAntriebsart.ToList());
        }

        // GET: Antriebsarts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAntriebsart tblAntriebsart = db.tblAntriebsart.Find(id);
            if (tblAntriebsart == null)
            {
                return HttpNotFound();
            }
            return View(tblAntriebsart);
        }

        // GET: Antriebsarts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Antriebsarts/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Antriebsart")] tblAntriebsart tblAntriebsart)
        {
            if (ModelState.IsValid)
            {
                db.tblAntriebsart.Add(tblAntriebsart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblAntriebsart);
        }
        public ActionResult CreateAntrieb()
        {
            if (ModelState.IsValid)
            {
                tblAntriebsart antr = new tblAntriebsart() { Antriebsart = "Test4" };
                db.tblAntriebsart.Add(antr);
                db.SaveChanges();                
            }
            return RedirectToAction("Index");
        }
        
        
        // GET: Antriebsarts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAntriebsart tblAntriebsart = db.tblAntriebsart.Find(id);
            if (tblAntriebsart == null)
            {
                return HttpNotFound();
            }
            return View(tblAntriebsart);
        }

        // POST: Antriebsarts/Edit/5
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDAA,Antriebsart")] tblAntriebsart tblAntriebsart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblAntriebsart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblAntriebsart);
        }

        // GET: Antriebsarts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAntriebsart tblAntriebsart = db.tblAntriebsart.Find(id);
            if (tblAntriebsart == null)
            {
                return HttpNotFound();
            }
            return View(tblAntriebsart);
        }

        // POST: Antriebsarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblAntriebsart tblAntriebsart = db.tblAntriebsart.Find(id);
            db.tblAntriebsart.Remove(tblAntriebsart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AMEL2/Controllers/BerichtsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AMEL2.Models;
using System.IO;
using AMEL2;
using System.Web.Security;

namespace AMEL2.Controllers
{    
    public class BerichtsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private tblAntriebsart TAntriebsart = new tblAntriebsart();
        private PandatasoftEntities1 db1 = new PandatasoftEntities1();
        //Bericht bericht = new Bericht() { };
        // GET: Berichts        
        static string _searchString;

        


        public void ExcelExport_old_ademsr(string sortOrder, string searchString)
        {
            StringWriter sw = new StringWriter();

            //First line for column names
            sw.WriteLine("\"ID\",\"Date\",\"Description\"");

            System.Collections.Generic.List<Bericht> list = getList_admser(sortOrder,  searchString);

            foreach (Bericht item in list)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\"",
                                           item.Projekt,
                                           item.s1,
                                           item.s2));
            }

            Response.AddHeader("Content-Disposition", "attachment; filename=Abtriebsliste EMSR.csv");
            Response.ContentType = "text/csv";
            Response.ContentEncoding = System.Text.Encoding.GetEncoding("utf-8");
            Response.Write(sw);
            Response.End();
        }

        

        public List<Bericht> getList_admser(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 22 && p.Projekt == 141303);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString));
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s1);
                    break;
            }
            return bers.ToList();
        }
       

        public ActionResult Index()
        {
            return View(db.Berichts.ToList());
        }
        
        // GET: Berichts



        public ActionResult old_ademsr(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 1 && p.Projekt== 170722);
            
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString) || p.s2.Contains(searchString) || p.s3.Contains(searchString) ||  p.s4.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString) || p.s2.Contains(_searchString) || p.s3.Contains(_searchString) || p.s4.Contains(_searchString));
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s4);
                    break;
            }
            ViewBag.TotalAgg = bers.Count();
            return View(bers.ToList());
        }


        public ActionResult old_advmt(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 1 && p.Projekt == 170722);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString) || p.s2.Contains(searchString) || p.s3.Contains(searchString) || p.s4.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString) || p.s2.Contains(_searchString) || p.s3.Contains(_searchString) || p.s4.Contains(_searchString));
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s4);
                    break;
            }
            return View(bers.ToList());
        }


        public ActionResult old_ab(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 1 && p.Projekt == 170722);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString) || p.s2.Contains(searchString) || p.s3.Contains(searchString) || p.s4.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString) || p.s2.Contains(_searchString) || p.s3.Contains(_searchString) || p.s4.Contains(_searchString)); 
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s4);
                    break;
            }
            return View(bers.ToList());
        }


        public ActionResult old_mdemsr(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 25 && p.Projekt == 141303);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString));
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s1);
                    break;
            }
            return View(bers.ToList());
        }


        public ActionResult old_mdvmt(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 26 && p.Projekt == 141303);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.Equals("All"))
                {
                    _searchString = String.Empty;
                    searchString = String.Empty;
                }
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                _searchString = searchString;
                bers = bers.Where(p => p.s1.Contains(searchString));
            }
            else
            {
                if (!String.IsNullOrEmpty(_searchString))
                {
                    bers = bers.Where(p => p.s1.Contains(_searchString));
                }
            }

            switch (sortOrder)
            {
                case "s1_desc":
                    bers = bers.OrderByDescending(s => s.s1);
                    break;
            }
            return View(bers.ToList());
        }



        public ActionResult old_msb(string sortOrder, string searchString)
        {
            ViewBag.s1SortParm = String.IsNullOrEmpty(sortOrder) ? "s1_desc" : "";
            var bers = from s in db.Berichts select s;
            bers = bers.Where(p => p.BN == 27 && p.Projekt == 141303);
            if (!String.IsNullOrEmpty(searchString))
            {

AMEL2/Views/Shared/_Layout.cshtml
@using AMEL2.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pandatasoft - </title>

    @{string text1 = "hallo"; }

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;)r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: 'ebd5eae7-882b-4ca7-a828-8169fcb95073'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
     
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Clausberg GmgH</a>
                <a class="navbar-brand" href="#">@text1</a>
                <a class="navbar-brand" href="#">@GlobalVariables.Email</a>
            </div>
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Startseite", "Index", "Home")</li>
                <li>@Html.ActionLink("Antriebsart", "Index", "Antriebsarts")</li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Aggregate<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @if (Request.IsAuthenticated && (HttpContext.Current.User.IsInRole("canEdit") || HttpContext.Current.User.IsInRole("canNoEdit")))
            {
                <li>@Html.ActionLink("Aggregatestammdaten", "old_ademsr", "Berichts")</li>
                <li>@Html.ActionLink("Aggregatemaschinendaten", "old_advmt", "Berichts")</li>
                <li>@Html.ActionLink("Zusätzliche Maschinendaten", "old_ab", "Berichts")</li>
}
else
{
            <li></li>
}
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Messstellen<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Aggregatestammdaten", "old_ademsr", "Berichts")</li>
                        <li>@Html.ActionLink("Aggregatemaschinendaten", "old_advmt", "Berichts")</li>
                        <li>@Html.ActionLink("Zusätzliche Maschinendaten", "old_ab", "Berichts")</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Anlagendokumentation", "old_mdvmt", "Berichts")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @*<li><a class="navbar-brand" href="#">@GlobalVariables.Email</a></li>*@
                @Html.Partial("_LoginPartial")
                @*<li>@Html.ActionLink("Reset PWD", "ResetPassword", "Account")</li>
                <li>@Html.ActionLink("Abmelden", "Logoff", "Home")</li>*@
            </ul>
        </div>
    </nav>



    <div class="rest container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016-@DateTime.Now.Year - Pandatasoft - </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>